<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 2025-2026 Larry Kramer

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>net.larrykramer</groupId>
  <artifactId>test-framework</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>Test Framework - Parent</name>
  <description>Parent project for the Test Framework and its modules</description>
  <url>https://github.com/larrykramer/test-framework</url>

  <organization>
    <name>Larry Kramer</name>
  </organization>

  <licenses>
    <license>
      <name>MIT License</name>
      <url>https://opensource.org/licenses/MIT</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <developers>
    <developer>
      <id>larrykramer</id>
      <name>Larry Kramer</name>
      <email>larry@larrykramer.net</email>
      <url>https://github.com/larrykramer</url>
    </developer>
  </developers>

  <modules>
    <module>test-framework-core</module>
    <module>test-suite</module>
  </modules>

  <scm>
    <connection>scm:git:https://github.com/larrykramer/test-framework.git</connection>
    <developerConnection>scm:git:https://github.com/larrykramer/test-framework.git</developerConnection>
    <tag>HEAD</tag>
    <url>https://github.com/larrykramer/test-framework</url>
  </scm>

  <issueManagement>
    <system>GitHub Issues</system>
    <url>https://github.com/larrykramer/test-framework/issues</url>
  </issueManagement>

  <distributionManagement>
    <repository>
      <id>github</id>
      <name>GitHub larrykramer Apache Maven Packages</name>
      <url>https://maven.pkg.github.com/larrykramer/test-framework</url>
    </repository>
  </distributionManagement>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    <maven.min.version>3.8.8</maven.min.version>
    <!--
      To build, this project requires a Java 21 or higher compiler, but with a
      Java 21 source and binary level.
      The project allows builds with a compiler version higher than 21 to
      allow testing on later releases.
    -->
    <maven.compiler.release>21</maven.compiler.release>
    <maven.compiler.target>${maven.compiler.release}</maven.compiler.target>
    <maven.compiler.source>${maven.compiler.release}</maven.compiler.source>

    <surefire.version>3.5.4</surefire.version>

    <!--
      Workaround for Surefire late variable replacement
      If 'surefire.system.args' is not present, Surefire will replace it
      verbatim, which will crash the VM
    -->
    <surefire.system.args/>

    <!--
      Dependency version properties begin here.

      Properties are grouped by whether they solely relate to plugins, solely
      relate to test code, or impact production code.

      Each version property should be of the form "<groupId>.version".
      For example, <org.seleniumhq.selenium.version>

      In cases where multiple artifacts use the same groupId but have different
      versions, add the artifactId or other qualifier to the property name.
      For example, <io.cucumber.gherkin.version>

      Version properties MUST be sorted alphabetically.
    -->

    <!--
      Plugin dependency versions.

      Named and ordered by their short name (antrun, clean, ...).

      This is not limited to plugin versions. Other artifacts that those plugins
      depend upon can go here if they are not otherwise used.
    -->
    <antrun.plugin.version>3.2.0</antrun.plugin.version>
    <clean.plugin.version>3.5.0</clean.plugin.version>
    <compiler.plugin.version>3.14.1</compiler.plugin.version>
    <dependency.plugin.version>3.9.0</dependency.plugin.version>
    <enforcer.plugin.version>3.6.2</enforcer.plugin.version>
    <surefire.plugin.version>${surefire.version}</surefire.plugin.version>
    <surefire-report.plugin.version>${surefire.version}</surefire-report.plugin.version>
    <!--
      TEST CODE dependency versions.
    -->
    <junit.version>4.13.2</junit.version>
    <org.mockito.version>5.21.0</org.mockito.version>
    <!--
      PRODUCTION CODE dependency versions.
    -->
    <io.cucumber.version>7.20.1</io.cucumber.version>
    <io.smallrye.smallrye-config.version>3.14.1</io.smallrye.smallrye-config.version>
    <jakarta.enterprise.version>4.1.0</jakarta.enterprise.version>
    <org.jboss.weld.se.version>6.0.3.Final</org.jboss.weld.se.version>
    <org.seleniumhq.selenium.version>4.38.0</org.seleniumhq.selenium.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>${junit.version}</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.mockito</groupId>
        <artifactId>mockito-core</artifactId>
        <version>${org.mockito.version}</version>
        <scope>test</scope>
      </dependency>

      <!-- CDI (Weld) -->
      <dependency>
        <groupId>jakarta.enterprise</groupId>
        <artifactId>jakarta.enterprise.cdi-api</artifactId>
        <version>${jakarta.enterprise.version}</version>
        <scope>provided</scope>
      </dependency>
      <dependency>
        <groupId>org.jboss.weld.se</groupId>
        <artifactId>weld-se-core</artifactId>
        <version>${org.jboss.weld.se.version}</version>
      </dependency>

      <!-- SmallRye Config -->
      <dependency>
        <groupId>io.smallrye.config</groupId>
        <artifactId>smallrye-config</artifactId>
        <version>${io.smallrye.smallrye-config.version}</version>
        <exclusions>
          <exclusion>
            <groupId>jakarta.enterprise</groupId>
            <artifactId>jakarta.enterprise.cdi-api</artifactId>
          </exclusion>
        </exclusions>
      </dependency>

      <!-- Cucumber -->
      <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-java</artifactId>
        <version>${io.cucumber.version}</version>
      </dependency>
      <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-core</artifactId>
        <version>${io.cucumber.version}</version>
      </dependency>
      <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-junit</artifactId>
        <version>${io.cucumber.version}</version>
        <scope>test</scope>
      </dependency>

      <!-- Selenium -->
      <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-java</artifactId>
        <version>${org.seleniumhq.selenium.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <!-- All plugins ordered by shortname (antrun, clean, ...) -->
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-antrun-plugin</artifactId>
          <version>${antrun.plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-clean-plugin</artifactId>
          <version>${clean.plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${compiler.plugin.version}</version>
          <configuration>
            <showDeprecation>true</showDeprecation>
            <showWarnings>true</showWarnings>
            <compilerArgs>
              <arg>-Xlint:unchecked</arg>
            </compilerArgs>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-dependency-plugin</artifactId>
          <version>${dependency.plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-enforcer-plugin</artifactId>
          <version>${enforcer.plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${surefire.plugin.version}</version>
          <configuration>
            <trimStackTrace>false</trimStackTrace>
            <argLine>@{surefire.system.args}</argLine>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-report-plugin</artifactId>
          <version>${surefire-report.plugin.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>

    <plugins>
      <!-- Check for the minimum version of Java and Maven. -->
      <!-- Runs during the validation phase. -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <executions>
          <execution>
            <id>enforce-java-version</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireJavaVersion>
                  <message>To build this project JDK ${maven.compiler.release} (or greater) is required. Please install it.</message>
                  <version>[${maven.compiler.release},)</version>
                </requireJavaVersion>
              </rules>
            </configuration>
          </execution>
          <execution>
            <id>enforce-maven-version</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireMavenVersion>
                  <message>To build this project Maven ${maven.min.version} (or greater) is required. Please install it.</message>
                  <version>[${maven.min.version},)</version>
                </requireMavenVersion>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
