name: 'Setup Java Environment'
description: 'Sets up a standardized Java environment with Maven caching and authentication for GitHub Packages.'

inputs:
  java-version:
    description: 'The Java version to set up (e.g., "21").'
    required: false
    default: '21'
runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v5
      with:
        distribution: 'oracle'
        java-version: ${{ inputs.java-version }}
        cache: 'maven'
        server-id: 'github'
